### ISSUE TITLE
Add support for non english languages.

### ISSUE THREAD

**Issue by Anish-M-code** [Anish-M-code/pdftotext#3]
Currently Pdftotext only supports english , potential contributors may try to add non english languages , simplify installation and uninstallation of additional language packs , add code to support above mentioned features on both linux and windows.

**Comment by pravincoder** [comment]
@Anish-M-code I can do it , but I think I might need your help !

**Comment by Anish-M-code** [comment]
Sure @pravincoder feel free to contribute and open pull request,  i can provide help if you need any.

**Comment by Anish-M-code** [comment]
Sure @pravincoder feel free to contribute and open pull request,  i can provide guidence if you need any.

**Comment by chirag4862** [comment]
Hi! Currently the package uses tesseract for ocr operations, I was thinking for multiple language support can I introduce a different onnx model other than tesseract?
With the Models bundled up with the package it will support both windows and linux without the requirement of tesseract already being installed in the system.

**Comment by Anish-M-code** [comment]
sure @chirag4862 we can try other models as well

**Comment by devfernandoa** [comment]
Hi there, is this still available? I've worked with something extremely similar to this and I'd love to help!
